name: escuela_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: 2.3.0
  shelf: 1.4.0
  shelf_router: 1.1.3
  watcher: 1.0.2
  supabase: ^0.2.9
  dart_mappable: 2.0.3
  mailer: ^6.0.0
  dotenv: ^4.1.0
  dart_jsonwebtoken: ^2.7.1
  shelf_helmet: ^1.1.0
  logger: ^1.3.0
  
 
  
 

dev_dependencies:
  build_runner: ^2.3.3
  dart_mappable_builder: ^2.0.2
  http: 0.13.0
  lints: 2.0.0
  test: 1.23.1
